languages = ["c", "cpp", "rust", "python"]

[compile]
c = "clang -std=c17 -o $target $source"
cpp = "clang++ -std=c++20 -o $target $source"
rust = "rustc -o $target $source"

[execute]
c = "$target"
cpp = "$target"
rust = "$target"
python = "python3 $source"

[compiler_output_channel]
c = "stderr"
cpp = "stderr"
rust = "stdout"
